### ISSUE TITLE
No prebuilt wheels with Python3.13

### ISSUE THREAD

**Issue by vivaansinghvi07** [emilydolson/python-phylogeny-tracker#108]
**Describe the bug**
There seem to be no wheels built for Python 3.13.

**To Reproduce**

Installation with Python 3.13 leads to building the code from scratch, which doesn't work on all platforms.

**Computational environment (please complete the following information):**
 - OS: MacOS Ventura Intel
 - Python version 3.13

**Comment by vivaansinghvi07** [comment]
Note: this will need the building of two wheels, one built for the version with the GIL and another for the experimental GIL-free version.

https://realpython.com/python313-free-threading-jit/#jit-compiles-python-to-machine-code

**Comment by emilydolson** [comment]
Release 0.2.3 should have wheels for Python 3.13, but not for the experimental version. Working on wheels for that now in #110

**Comment by emilydolson** [comment]
Okay, I think it should all be working!
