### ISSUE TITLE
Allow real-time collapsing of unifurcations to save space

### ISSUE THREAD

**Issue by emilydolson** [emilydolson/python-phylogeny-tracker#19]
This should actually happen in Empirical, but I'm putting this issue here so we don't lose it.

@mmore500 had a good point today about how we can collapse the "stem" of the phylogeny after coalescence events to save space. However, it won't help is in the (relatively common) case where we have a couple very deep branches maintained forever by ecological dynamics. However, we could handle both cases by allowing all unifurcations to be collapsed in real time. This could potentially save a decent amount of space.

**Comment by mmore500** [comment]
Post-hoc collapsing of unifurcations would also be very valuable to ensure consistent phylometric results. Alternately, it looks like in Empirical `branch_only` options are defaulted to `false` and it might make more sense to default them to `true`?
