### ISSUE TITLE
Outstanding API documentation changes

### ISSUE THREAD

**Issue by rodsan0** [emilydolson/python-phylogeny-tracker#22]
- [x] Write/find section comparing positional to non-positional tracking
    - [x] Link it in the `set_store_position` docstring
- [x] Test nullptr -> None conversion in `parent()` and beyond
- [x] Add support for [Sphinx Tippy](https://sphinx-tippy.readthedocs.io/en/latest/) or some other tool tip extension
- [x] Add Sphinx bibliographies (can be based on Empirical implementation)
- [ ] Change all "systematics manager" to "phylotrackpy"

**Comment by emilydolson** [comment]
I don't think we actually need to change mentions of the systematics manager to phylotrackpy, since it's the phylotrackpy systematics manager

**Comment by emilydolson** [comment]
Last fixes done in #84
