### ISSUE TITLE
Document the funky stuff I just did with deep copies of taxon objects

### ISSUE THREAD

**Issue by emilydolson** [emilydolson/python-phylogeny-tracker#29]
Basically, there is no time you should ever make a copy of a taxon object (counterexamples welcome, but I'm pretty sure there's not). However, you might want to have one be part of your organism class and make a deep copy of an organism. To make this possible, I have added a fake deepcopy operator to the taxon object. Obviously, that has the potential to be super confusing (and I'm open to alternative approaches to this one), so we should document it really clearly.

**Comment by mmore500** [comment]
Are taxa mutable?--
Matthew Andres Moreno
https://mmore500.github.io

**Comment by emilydolson** [comment]
Good question. In practice, they are from the Python side in that there are no methods that allow you to change them. I'm not sure if Python officially sees them as immutable.
