### ISSUE TITLE
JOSS Review: Functionality, documentation

### ISSUE THREAD

**Issue by CFGrote** [emilydolson/python-phylogeny-tracker#34]
[JOSS Review issue](https://github.com/openjournals/joss-reviews/issues/5754)

# General documentation
I very much appreciate the detailled introduction and explanations regarding the subtleties in running in-silico vs. in-vitro or in-vivo phylogenetic tracking.

# Usage example
 That being said, I'm missing similar in-depth usage instructions at a more concrete level than what is
provided in the docs. The usage example does not go beyond showing how to instantiate the `Systematics` class. What can I do with the class from there on? I tried adding an organism, but needed to mock up an `Organism` class first. Unfortunately, I'm left
entirely on my own with that task. Would be helpful to have some minimum requirements for such an object or even better a template (abstract base class).

# Writing an Organism class
 Here's my attempt:

```
from phylotrackpy import systematics

syst = systematics.Systematics(lambda org: org.genotype)

class Organism():
    genotype = "ACTG"


org0 = Organism()

org0.genotype

syst.add_org(org0)
```

This code lived in a jupyter notebook, executing the last line of code crashed the kernel.

# Coding style
I would recommend not to use `sys` for a local variable name as it obscures the python native library of the same name (which many python codes import)

# Usage example recommendation
For a proper usage example I would expect to be instructed how to build a phylogeny from scratch and how to analyse it. You could also provide the data for below figure (from the README) and instruct the user how to reproduce it.

![Copied from README.md](https://github.com/emilydolson/phylotrackpy/raw/main/docs/images/FullPhylogeny.png)

# API documentation
Please complete the API documentation and, if done, remove the note "Partially under construction". Probably related to #13 and #22

**Comment by RussellGarwood** [comment]
[JOSS Review issue](https://github.com/openjournals/joss-reviews/issues/5754)

I am also reviewing this for JOSS, and one of my requests was going to be a usage example - so I thought I would just note here that I concur, this would be a very valuable addition!

**Comment by emilydolson** [comment]
Thank you for these very helpful comments! It is so helpful to have an external perspective on where stuff like documentation could be clearer and I really appreciate it (even if though it took me forever to get it fixed!).

I think that we've now addressed all of these points in the documentation. Just to call out a few particularly important components:
- Example usage is here: https://phylotrackpy.readthedocs.io/en/latest/example_usage.html
- Your organism example actually should have worked. I have fixed the underlying bug, added a test enforcing that it works, and attempted to further clarify the documentation

I'm going to close this (finally!) for now, but feel free to reopen it if you think there's anything we didn't address satisfactorily
