### ISSUE TITLE
JOSS Review: Paper

### ISSUE THREAD

**Issue by CFGrote** [emilydolson/python-phylogeny-tracker#35]
[JOSS Review issue](https://github.com/openjournals/joss-reviews/issues/5754)

The paper reads great and leaves only few minor details to be desired:

- line 164: Ref. "Moreno et al (under review)" seems to be unpublished, is it possible to link to a preprint instead?
- There is no URL link for the reference to pybind (Jakob, 2017).

**Comment by RussellGarwood** [comment]
[JOSS Review issue](https://github.com/openjournals/joss-reviews/issues/5754)

I note the paper states the software can "support large agent populations with rapid generational turnover" - it might be useful in this section to indicate ballpark figures for large, and rapid, within this context, as I imagine this differs a good deal between models.

**Comment by mmore500** [comment]
We still need to put up the preprints and cite them 👍

**Comment by emilydolson** [comment]
Thanks so much for these suggestions! Profiling info has been added to the paper, we have preprinted the supporting papers, and cited them (thanks @mmore500!). I believe this covers everything.
