### ISSUE TITLE
JOSS Review: Input data format conversion

### ISSUE THREAD

**Issue by CFGrote** [emilydolson/python-phylogeny-tracker#36]
[JOSS Review issue](https://github.com/openjournals/joss-reviews/issues/5754)

This is not a critical review issue but I came across it while reviewing:

**Is your feature request related to a problem? Please describe.**
Reading phylogenies stored in foreign file formats seems not to be supported. 

**Describe the solution you'd like**
I'm running stochastic simulations and store the resulting trajectories in a newick tree file or in a json document. Now I want to analyse my data with phylotracks. How can I get the data into phylotracks?

**Comment by emilydolson** [comment]
Thanks so much for this suggestion! @mmore500 has added support for this via his alifedata-phyloinformatics-convert library, which is designed to handle translation among the format used by phylotrackpy and more standard bioinformatics formats. We have added documentation to the quickstart guide explaining how to use it. I'm going to close this for now, but if you see ways the documentation on it could be improved let me know!
