### ISSUE TITLE
`get_ave_depth` NaN

### ISSUE THREAD

**Issue by mmore500** [emilydolson/python-phylogeny-tracker#5]
**Describe the bug**
`get_ave_depth` returns NaN

**To Reproduce**

```
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from phylotrackpy import systematics
>>> sys = systematics.Systematics(lambda x: x)
>>> sys.load_from_file("consolidated.csv", "id", True)
>>> sys
<phylotrackpy.systematics.Systematics object at 0x7f122983d770>
>>> sys.get_ave_depth()
nan
```
[consolidated.csv](https://github.com/emilydolson/phylotrackpy/files/10929222/consolidated.csv)

**Expected behavior**
I think `get_ave_depth()` should return a defined value for this tree?

**Computational environment (please complete the following information):**
 - OS: popOS
 - Python version 3.10

**Additional context**

phylotrackpy version 0.1.12

**Comment by emilydolson** [comment]
Fixed in latest version!
