### ISSUE TITLE
`load_from_file` takes >10 min for large files

### ISSUE THREAD

**Issue by mmore500** [emilydolson/python-phylogeny-tracker#6]
**Describe the bug**
The `load_from_file` function takes suspiciously long to load big data files (~400k rows).

**To Reproduce**

```
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from phylotrackpy import systematics
>>> sys = systematics.Systematics(lambda x: x)
>>> sys.load_from_file("full.csv", "id", True)
```
[full.csv](https://github.com/emilydolson/phylotrackpy/files/10929338/full.csv)

**Expected behavior**
go fast(er)! :sweat_smile: 

**Screenshots**

**Computational environment (please complete the following information):**
 - OS: popOS
 - Python version 3.10

**Additional context**
phylotrackpy version 0.1.12

**Comment by mmore500** [comment]
ok! it didn't hang --- it loaded but took somewhere between 15 and 30 minutes

**Comment by mmore500** [comment]
computing metrics doesn't take as long as loading --- `get_variance_pairwise_distance(True)` took about 3 seconds which is totally fine.

**Comment by emilydolson** [comment]
I've got it down to ~3 minutes. The remaining time is basically all being taken by the depth correction. I think maybe I'll make it optional so that if users don't need it they can skip it.

EDIT: I meant the total number of offspring correction. The depth correction is not that slow.

**Comment by emilydolson** [comment]
Fixed! Load time should be substantially faster in general. If you need even more speed you can also pass a flag to `load_from_file` to have it not do the total number of offspring correction, which will make it very fast. Note that this should only be done by people who know what they're doing, as it could break other stuff (mostly evolutionary distinctiveness)
