### ISSUE TITLE
`colless_like_index` crashes for empty tree

### ISSUE THREAD

**Issue by mmore500** [emilydolson/python-phylogeny-tracker#83]
**Describe the bug**
Calculation of colless-like index crashes on empty trees

**To Reproduce**
```python3
>>> from phylotrackpy import systematics
>>> syst = systematics.Systematics(lambda x: x)
>>> syst.colless_like_index()
```

**Expected behavior**
Shouldn't crash.
Should give numerical result (perhaps `NaN`).

**Computational environment (please complete the following information):**
 - OS: Fedora
 - Python version 3.12.2

**Additional context**
v0.2.0

**Comment by emilydolson** [comment]
Fixed in #100 (decided to just go with it returning 0)
